"""Unified pipeline configuration: dataclasses, YAML I/O and validation.

The config file has one section per pipeline step (``dem``, ``gfm``, ``flexth``, ``ghsl``)
plus shared ``project`` and ``aoi`` sections. All paths in the file are
interpreted relative to the directory containing the YAML file, so the config
stays portable across machines.

The ``flexth`` section is a raw dict passthrough: it is copied verbatim into
the generated FLEXTH config (see :mod:`flood_pipeline.steps.flexth_step`), so
this module does not duplicate FLEXTH's own schema.
"""

from __future__ import annotations

import dataclasses
import datetime
import re
from dataclasses import dataclass, field
from pathlib import Path

import yaml


class ConfigError(Exception):
    """Raised when the pipeline config file cannot be loaded or parsed."""


DEM_DELIVERY_MODES = ("local", "drive")
GFM_AGGREGATIONS = ("max", "sum", "both")
GFM_SCENE_PREFIX = "gfm_flood"
GFM_MAX_NAME = f"{GFM_SCENE_PREFIX}_max.tif"
GFM_SUM_NAME = f"{GFM_SCENE_PREFIX}_sum.tif"
# Static per-AOI reference layer of permanent water; one download per project.
GFM_REFERENCE_WATER_NAME = f"{GFM_SCENE_PREFIX}_reference_water.tif"
# The four GFM flood-detection algorithms, key -> STAC band name. Insertion
# order is the order compare-mode processes and lists them.
GFM_ALGORITHM_BANDS = {
    "ensemble": "ensemble_flood_extent",
    "dlr": "dlr_flood_extent",
    "tuw": "tuw_flood_extent",
    "list": "list_flood_extent",
}
GFM_LIKELIHOOD_SUFFIX = "_likelihood"
# Bands offered in the Config UI picker: the four algorithm extents plus the
# ensemble likelihood (thresholded into an extent by the gfm step).
GFM_SELECTABLE_BANDS = list(GFM_ALGORITHM_BANDS.values()) + ["ensemble_likelihood"]
SCENE_STAMP_FORMAT = "%Y-%m-%d_%H%M%S"  # UTC acquisition timestamp, filename-safe
# Per-scene rasters live in a per-scene folder that carries the stamp, so their
# own filenames are fixed (no stamp suffix).
GFM_SCENE_NAME = f"{GFM_SCENE_PREFIX}.tif"  # "gfm_flood.tif"
GFM_EXCLUSION_NAME = "gfm_exclusion.tif"  # pixels GFM could not evaluate (overlay)
# Raw 0-100 likelihood kept beside a thresholded likelihood-band scene (overlay).
GFM_LIKELIHOOD_NAME = "gfm_likelihood.tif"
# Pixels FLEXTH flooded beyond the raw GFM extent (the interpolation's addition).
GFM_FILL_NAME = "interpolated_fill.tif"
# Connected flood areas derived from a flood raster live next to it, same stem.
GFM_VECTOR_SUFFIX = ".gpkg"
FLOOD_AREA_LAYER = "flood_areas"
# A bare acquisition stamp, as SCENE_STAMP_FORMAT renders it. Scene work, output
# and data folders are named after it alone.
STAMP_PATTERN = r"\d{4}-\d{2}-\d{2}_\d{6}"
SCENE_DIR_RE = re.compile(rf"^{STAMP_PATTERN}$")
# io and merge are generated by flexth_step; only these keys may appear here.
# fill_excluded is consumed by flexth_step, not passed through to FLEXTH.
FLEXTH_ALLOWED_KEYS = {
    "enabled",
    "resample",
    "prepare_dtm",
    "flood_processing",
    "fill_excluded",
}


def band_key(band_name: str) -> str:
    """Short, filesystem-safe folder key for a GFM band name.

    ``ensemble_flood_extent`` -> ``ensemble``; unknown names are sanitized.
    """
    for suffix in ("_flood_extent", "_water_extent"):
        if band_name.endswith(suffix):
            return band_name[: -len(suffix)]
    return re.sub(r"[^0-9A-Za-z._-]", "_", band_name)


def is_likelihood_band(band_name: str) -> bool:
    """True for GFM likelihood bands, which are thresholded into an extent."""
    return band_name.endswith(GFM_LIKELIHOOD_SUFFIX)


@dataclass
class ProjectConfig:
    """Run name, GEE cloud project and the data directories.

    A project is a folder containing its own config.yaml; the data dirs (and
    the AOI) resolve relative to that folder unless they are absolute.
    """

    name: str = "flood_run"
    gee_project: str = ""
    data_dir: str = "flood_data"
    work_dir: str = "preprocessed"
    output_dir: str = "wl_wd_out"


@dataclass
class DemConfig:
    """FABDEM DEM retrieval via Google Earth Engine."""

    enabled: bool = True
    delivery: str = "local"  # "local" download | "drive" export (pipeline halts)
    scale: int = 30
    crs: str = "EPSG:4326"
    out_name: str = "fabdem.tif"
    overwrite: bool = False
    drive_folder: str = "fabdem_exports"
    drive_prefix: str = "fabdem"


@dataclass
class GfmConfig:
    """GFM flood-extent retrieval via the EODC STAC API."""

    enabled: bool = True
    stac_url: str = "https://stac.eodc.eu/api/v1"
    collection: str = "GFM"
    band: str = "ensemble_flood_extent"
    temporal_extent: list[str] = field(
        default_factory=lambda: ["2024-09-15", "2024-09-20"]
    )
    resolution: float = 0.0003  # degrees (EPSG:4326)
    max_items: int = 0  # optional safety cap on scenes loaded; 0 = fetch all
    aggregation: str = "max"  # "max" | "sum" | "both"; max is always written
    min_area_ha: float = 1.0  # smallest connected flood area kept; 0 = no filter
    compare_algorithms: bool = False  # run all four algorithm bands, not just `band`
    likelihood_threshold: int = 25  # percent; only used for a *_likelihood band


@dataclass
class GhslConfig:
    """GHSL settlement characteristics extraction via Google Earth Engine."""

    enabled: bool = True
    asset: str = "JRC/GHSL/P2023A/GHS_BUILT_C/2018"
    band: str = "built_characteristics"
    scale: int = 10
    crs: str = "EPSG:4326"


@dataclass
class PipelineConfig:
    """The full unified config plus the location it was loaded from."""

    project: ProjectConfig
    aoi_path: str
    dem: DemConfig
    gfm: GfmConfig
    flexth: dict
    ghsl: GhslConfig
    source_path: Path

    def resolve(self, relative: str | Path) -> Path:
        """Resolve a config path against the config file's directory."""
        path = Path(relative)
        if path.is_absolute():
            return path
        return (self.source_path.parent / path).resolve()

    @property
    def project_dir(self) -> Path:
        """The project folder: the directory the config file lives in."""
        return self.source_path.parent

    @property
    def data_dir(self) -> Path:
        return self.resolve(self.project.data_dir)

    @property
    def work_dir(self) -> Path:
        return self.resolve(self.project.work_dir)

    @property
    def output_dir(self) -> Path:
        return self.resolve(self.project.output_dir)

    @property
    def aoi_abs_path(self) -> Path:
        return self.resolve(self.aoi_path)

    def resolved_bands(self) -> list[tuple[str, str]]:
        """(key, STAC band name) pairs to process this run.

        All four algorithms when ``gfm.compare_algorithms``, else the single
        configured ``gfm.band`` (its key derived from the band name).
        """
        if self.gfm.compare_algorithms:
            return list(GFM_ALGORITHM_BANDS.items())
        return [(band_key(self.gfm.band), self.gfm.band)]

    def dem_path(self) -> Path:
        """The DEM raster the dem step produces and FLEXTH consumes."""
        return self.data_dir / self.dem.out_name

    def gfm_band_dir(self, band: str) -> Path:
        """The per-band data folder holding that band's scenes and aggregates."""
        return self.data_dir / band

    def gfm_scene_dir(self, band: str, stamp: str) -> Path:
        """One acquisition's folder for a band (holds gfm_flood.tif etc.)."""
        return self.gfm_band_dir(band) / stamp

    def gfm_scene_path(self, band: str, stamp: str) -> Path:
        """Per-scene flood mask for a band/timestamp."""
        return self.gfm_scene_dir(band, stamp) / GFM_SCENE_NAME

    def gfm_exclusion_path(self, band: str, stamp: str) -> Path:
        """Per-scene exclusion mask for a band/timestamp (overlay only)."""
        return self.gfm_scene_dir(band, stamp) / GFM_EXCLUSION_NAME

    def gfm_likelihood_path(self, band: str, stamp: str) -> Path:
        """Raw likelihood raster for a likelihood-band scene (overlay/probe)."""
        return self.gfm_scene_dir(band, stamp) / GFM_LIKELIHOOD_NAME

    def gfm_mask_path(self, band: str) -> Path:
        """Whole-time max flood mask at the band root (reference/overlay)."""
        return self.gfm_band_dir(band) / GFM_MAX_NAME

    def gfm_sum_path(self, band: str) -> Path:
        """The optional temporal-sum raster at the band root."""
        return self.gfm_band_dir(band) / GFM_SUM_NAME

    def gfm_reference_water_path(self, band: str) -> Path:
        """Static permanent-water reference mask at the band root."""
        return self.gfm_band_dir(band) / GFM_REFERENCE_WATER_NAME

    def gfm_scene_stamps(self, band: str) -> list[str]:
        """Acquisition stamps of a band, discovered from its scene folders."""
        band_dir = self.gfm_band_dir(band)
        if not band_dir.exists():
            return []
        return sorted(
            p.name
            for p in band_dir.iterdir()
            if p.is_dir() and SCENE_DIR_RE.match(p.name)
        )

    def scene_work_root(self, band: str) -> Path:
        """FLEXTH work root for a band (holds one subfolder per scene)."""
        return self.work_dir / band

    def scene_output_root(self, band: str) -> Path:
        """FLEXTH output root for a band (holds one subfolder per scene)."""
        return self.output_dir / band

    def scene_work_dir(self, band: str, stamp: str) -> Path:
        """FLEXTH work dir for one band/scene (own flood.tif/dtm.tif)."""
        return self.scene_work_root(band) / stamp

    def scene_output_dir(self, band: str, stamp: str) -> Path:
        """FLEXTH output dir for one band/scene's WD_/WL_ rasters."""
        return self.scene_output_root(band) / stamp

    def scene_fill_path(self, band: str, stamp: str) -> Path:
        """Raster of pixels FLEXTH flooded beyond the raw GFM extent (overlay)."""
        return self.scene_output_dir(band, stamp) / GFM_FILL_NAME

    def scene_ghsl_depth_path(self, stamp: str) -> Path:
        """Path to the per-scene combined GHSL + water depth raster."""
        return self.output_dir / f"ghsl_depth_{stamp}.tif"

    def scene_fill_path(self, band: str, stamp: str) -> Path:
        """Raster of pixels FLEXTH flooded beyond the raw GFM extent (overlay)."""
        return self.scene_output_dir(band, stamp) / GFM_FILL_NAME

    def gfm_output_bands(self) -> list[str]:
        """Band keys that have at least one scene output folder on disk."""
        if not self.output_dir.exists():
            return []
        scenes = [
            p
            for p in self.data_dir.glob(GFM_SCENE_NAME)
            if GFM_SCENE_STAMP_RE.search(p.name)
        ]
        return sorted(scenes, key=lambda p: p.name)

    def ghsl_path(self) -> Path:
        """Path to the downloaded base GHSL raster for the AOI."""
        return self.data_dir / "ghsl_built.tif"

def vector_path(raster: Path) -> Path:
    """The flood-area polygon file belonging to a flood raster.

    A plain name derivation (``…/gfm_flood_max.tif`` -> ``…/gfm_flood_max.gpkg``),
    so it is a free function rather than a :class:`PipelineConfig` method: it
    serves scene, max and test paths alike without needing any config state.
    """
    return raster.with_suffix(GFM_VECTOR_SUFFIX)


def _as_iso_date(value: object) -> str:
    """Normalize a YAML date value (str, date or datetime) to YYYY-MM-DD."""
    if isinstance(value, datetime.datetime):
        return value.date().isoformat()
    if isinstance(value, datetime.date):
        return value.isoformat()
    return str(value)


def _section_to_dataclass[T](cls: type[T], raw: dict, section: str) -> T:
    known_fields = {f.name for f in dataclasses.fields(cls)}
    values = raw.get(section) or {}
    if not isinstance(values, dict):
        raise ConfigError(f"'{section}' section must be a mapping, got {values!r}")
    unknown = set(values) - known_fields
    if unknown:
        raise ConfigError(f"unknown keys in '{section}' section: {sorted(unknown)}")
    return cls(**values)


def load_config(path: str | Path) -> PipelineConfig:
    """Load and structurally check a unified config file.

    Raises:
        ConfigError: If the file is missing, not valid YAML, or contains
            unknown keys in the sections this module owns.
    """
    path = Path(path)
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError as e:
        raise ConfigError(f"config file not found: {path}") from e
    try:
        raw = yaml.safe_load(text) or {}
    except yaml.YAMLError as e:
        raise ConfigError(f"config file is not valid YAML: {path}\n{e}") from e
    if not isinstance(raw, dict):
        raise ConfigError(f"config root must be a mapping: {path}")

    gfm = _section_to_dataclass(GfmConfig, raw, "gfm")
    gfm.temporal_extent = [_as_iso_date(v) for v in gfm.temporal_extent]
    aoi_section = raw.get("aoi") or {}

    return PipelineConfig(
        project=_section_to_dataclass(ProjectConfig, raw, "project"),
        aoi_path=str(aoi_section.get("path", "aoi.gpkg")),
        dem=_section_to_dataclass(DemConfig, raw, "dem"),
        gfm=gfm,
        flexth=raw.get("flexth") or {},
        ghsl=_section_to_dataclass(GhslConfig, raw, "ghsl"),
        source_path=path.resolve(),
    )


def to_dict(cfg: PipelineConfig) -> dict:
    """Convert a config back to the plain-dict form used in the YAML file."""
    return {
        "project": dataclasses.asdict(cfg.project),
        "aoi": {"path": cfg.aoi_path},
        "dem": dataclasses.asdict(cfg.dem),
        "gfm": dataclasses.asdict(cfg.gfm),
        "flexth": cfg.flexth,
        "ghsl": dataclasses.asdict(cfg.ghsl),
    }


def save_config(cfg: PipelineConfig, path: Path | None = None) -> None:
    """Write the config as YAML to ``path`` (default: where it was loaded from).

    Note: PyYAML does not preserve comments; the schema is documented in the
    README instead.
    """
    target = Path(path) if path is not None else cfg.source_path
    target.write_text(
        yaml.safe_dump(to_dict(cfg), sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )


def _temporal_extent_errors(extent: list[str]) -> list[str]:
    if len(extent) != 2:
        return [f"gfm.temporal_extent must be [start, end], got {extent!r}"]
    try:
        start = datetime.date.fromisoformat(extent[0])
        end = datetime.date.fromisoformat(extent[1])
    except ValueError:
        return [f"gfm.temporal_extent dates must be ISO (YYYY-MM-DD), got {extent!r}"]
    if start > end:
        return [f"gfm.temporal_extent start is after end: {extent!r}"]
    return []


def validate(cfg: PipelineConfig) -> list[str]:
    """Check the config for problems; an empty list means it is runnable."""
    errors: list[str] = []
    if not cfg.aoi_abs_path.exists():
        errors.append(f"AOI file not found: {cfg.aoi_abs_path}")
    if cfg.dem.delivery not in DEM_DELIVERY_MODES:
        errors.append(
            f"dem.delivery must be one of {DEM_DELIVERY_MODES}, got {cfg.dem.delivery!r}"
        )
    if cfg.dem.enabled and not cfg.project.gee_project:
        errors.append("project.gee_project must be set when the dem step is enabled")
    if cfg.ghsl.enabled and cfg.ghsl.scale <= 0:
        errors.append("ghsl.scale must be greater than 0")
    if cfg.gfm.aggregation not in GFM_AGGREGATIONS:
        errors.append(
            f"gfm.aggregation must be one of {GFM_AGGREGATIONS}, got {cfg.gfm.aggregation!r}"
        )
    if cfg.gfm.min_area_ha < 0:
        errors.append(
            f"gfm.min_area_ha must be >= 0 (0 disables the filter), "
            f"got {cfg.gfm.min_area_ha!r}"
        )
    if is_likelihood_band(cfg.gfm.band) and not 1 <= cfg.gfm.likelihood_threshold <= 100:
        errors.append(
            f"gfm.likelihood_threshold must be 1..100 for band {cfg.gfm.band!r}, "
            f"got {cfg.gfm.likelihood_threshold!r}"
        )
    errors.extend(_temporal_extent_errors(cfg.gfm.temporal_extent))
    unknown = set(cfg.flexth) - FLEXTH_ALLOWED_KEYS
    if unknown:
        errors.append(
            f"unknown keys in 'flexth' section: {sorted(unknown)} "
            f"(io and merge are generated automatically)"
        )
    return errors